version: '3.8'

services:
  # Konfigurasi Database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: siakng_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123 # Ganti dengan password yang lebih aman jika perlu
      POSTGRES_DB: siakng_lite
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    # networks:
    #   - siakng_network

  # Konfigurasi Backend NestJS (Persiapan)
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: siakng_backend
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   environment:
  #     # URL ini akan digunakan oleh ORM untuk terhubung ke database
  #     DATABASE_URL: postgresql://postgres:password123@postgres:5432/siakng_lite?schema=public
  #   networks:
  #     - siakng_network

volumes:
  # Volume persisten agar data tabel tidak hilang saat container dimatikan
  pgdata:

# networks:
#   siakng_network:
#     driver: bridge
